language: node_js
node_js:
  - "8"

jobs:  
  include:
    - stage: "js"
      install: npm install -g jshint
      script: jshint static/js
    - stage: "css"
      install: npm install -g csslint
      script: csslint static/css
